



spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1/dbgirl?useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
